# These are supported funding model platforms

 github: robbieallover
bitcoin: bc1pjs39u48ajkd273cuylycvpp73mp9szfmjjycvnj8drurxf4md50qzmjexe
bitcoin: bc1qw0fs38h7w4zv7uscu3776vtnp9773p37pg27yk
bitcoin: 1D42jjdg2WMvdkDLRavyW74dw3fnScn6zD
bitcoin: 3QaHc7petmP8atPcesbf8oXNh4pjnHCsPv

